package:
    name: scan2
    version: "2.0"

build:
    number: 2

requirements:
    run:
      - python=3.8
      - snakemake
      - mamba
      - drmaa
      - shapeit
      - eagle-phase
      - gatk
      - gatk4
      - samtools
      - pysam
      - bedtools
      - htslib
      - bcftools
      - r-scan2
      - shyaml

source:
    git_url: https://github.com/parklab/SCAN2.git

about:
    home: https://github.com/parklab/SCAN2
    summary: Somatic SNV and indel genotyper for PTA-amplified single cells
