package:
    name: scan2
    version: "2.0"

requirements:
    run:
      - snakemake
      - mamba
      - drmaa
      - r-base
      - bioconductor-annotatr
      - bioconductor-regioner
      - r-pracma
      - r-yaml
      - pysam
      - bioconductor-bsgenome.hsapiens.1000genomes.hs37d5
      - bioconductor-bsgenome.hsapiens.ucsc.hg19
      - bioconductor-bsgenome.hsapiens.ucsc.hg38
      - bioconductor-bsgenome.hsapiens.ncbi.grch38
      - r-fastghquad
      - bedtools
      - htslib
      - gatk
      - gatk4
      - samtools
      - r-viridis
      - bcftools
      - r-upsetr
      - r-future.apply
      - r-vioplot
      - r-pbapply
      - r-plyr
      - r-scan2
      - shapeit

source:
    git_url: https://github.com/parklab/SCAN2.git

about:
    home: https://github.com/parklab/SCAN2
    summary: SNV genotyper for PTA-amplified single cells
